const songData = [
    {
        "id": "1",
        "artists": "Artist1",
        "album": "Album1",
        "title": "Song 1",
        "popularity": 85,
        "duration_ms": 200000,
        "explicit": false,
        "danceability": 0.8,
        "energy": 0.7,
        "key": 5,
        "loudness": -5,
        "mode": 1,
        "speechiness": 0.05,
        "acousticness": 0.1,
        "instrumentalness": 0,
        "liveness": 0.1,
        "valence": 0.9,
        "tempo": 100,
        "genre": "Soca"
    },
    {
        "id": "2",
        "artists": "Artist2",
        "album": "Album2",
        "title": "Song 2",
        "popularity": 75,
        "duration_ms": 180000,
        "explicit": true,
        "danceability": 0.9,
        "energy": 0.85,
        "key": 8,
        "loudness": -4,
        "mode": 1,
        "speechiness": 0.04,
        "acousticness": 0.2,
        "instrumentalness": 0,
        "liveness": 0.15,
        "valence": 0.8,
        "tempo": 110,
        "genre": "Dancehall"
    }
];